### ISSUE TITLE
DEBUG logs are overwriting each other

### ISSUE THREAD

**Issue by joerg-eyring** [miyako/4d-plugin-curl-v3#11]
Hi Keisuke,

just a suggestion for future versions: Sometimes we're using cURL and/or cURL ftp in several (parallel) processes at the same time and are observing that the DEBUG logs are overwritten by each other. Maybe you want to consider adding a date/timestamp to the log file names so they're being preserved for later analysis.

Thanks and regards, Jörg

**Comment by miyako** [comment]
I don't understand why one wpuld use both plugins.

does not v3 support ftp as well?

**Comment by joerg-eyring** [comment]
You misunderstood me: Of course we're using ONLY ONE plugin (cURL.bundle). This plugin supports either "cURL" or "cURL ftp"). So back to my suggestion: For instance we're uploading files with cURL ftp in parallel processes and we are observing that the DEBUG logs are overwritten by each other…

**Comment by miyako** [comment]
I am thinking of adding a new option `DEBUG_ID`.

it will be a folder name if passed.

**Comment by miyako** [comment]
you can try with 4.3.0
