### ISSUE TITLE
Error 3 with Mac and space in URL

### ISSUE THREAD

**Issue by FabienArr** [miyako/4d-plugin-curl-v3#16]
Hi Keisuke,

With the last release of cURL 4.4.12, we discover a bug when the URL contains spaces. 
In download or upload, if the URL contain a space we got error 3. It's occur only on mac not on windows.
If you need more explanations i'm open.

Regards

**Comment by FabienArr** [comment]
I don't think so :

//Test upload
$Turl:="sftp://home173627097.1and1-data.host/"
C_OBJET($Oftp)
OB FIXER($Oftp; \
"URL"; $Turl; \
"USERNAME"; "u1688469212"; \
"PASSWORD"; "azertyuiop12345;"; \
"USE_SSL"; "1"; \
"FTP_SSL_CCC"; "CCC_ACTIVE")
$Tfichier:="C:\\Users\\Fabien\\Documents\\Points 220713104236.txt"
$Oftp.READDATA:=$Tfichier
$Oftp.URL:=$Turl+"Points 220713104236.txt" //**Here the space in URL**

$Lerreur:=qCu0_LFtpTransfert($Oftp)

**Comment by FabienArr** [comment]
Ok thanks, but why it occurs only on Mac and not on Windows ?

**Comment by miyako** [comment]
> i need to split all the URL on the / for not escape only this character ?

yes. you must apply the escape to a string value, not the entire URL.

https://curl.se/libcurl/c/curl_easy_escape.html
