### ISSUE TITLE
Date and time

### ISSUE THREAD

**Issue by MatthieuLamp** [miyako/4d-plugin-curl-v3#18]
Hi

When obtaining the list of directories, is it possible to obtain the date and time of modification?

**Comment by miyako** [comment]
currently

`cURL_FTP_GetDirList` returns 

* the raw response in `dirList` (text)
* more information from `ftpparse` (collection)

the precision of `mtime` depends on the server response. 
the plugin sends the FTP `LIST` command.
if `mtimetype` is `REMOTEDAY` the time would be missing.

https://everything.curl.dev/ftp/dirlist

perhaps it should send `MLSD`

**Comment by miyako** [comment]
`ftpaparse` doesn't support `MLSD` so the text is detailed but the collection becomes empty.

**Comment by miyako** [comment]
https://github.com/miyako/4d-plugin-curl-v3/releases/tag/4.5.0
