### ISSUE TITLE
bug Big Sur

### ISSUE THREAD

**Issue by MatthieuLamp** [miyako/4d-plugin-curl-v3#19]
Hi,

version 4.5.0 crashes 4D on startup on macOS Big Sur, Intel

**Comment by MatthieuLamp** [comment]
no problem with macOS 14 on M2

**Comment by miyako** [comment]
I am sorry I don't have big Sur so it is impossible to validate or fix such issues with no detailed information.

**Comment by miyako** [comment]
are you saying that it was OK before https://github.com/miyako/4d-plugin-curl-v3/issues/18 ?

**Comment by miyako** [comment]
what about macOS 14 on M2 but Rosetta?

**Comment by MatthieuLamp** [comment]
> are you saying that it was OK before #18 ?

it's ok with release 4.4.12

**Comment by MatthieuLamp** [comment]
> what about macOS 14 on M2 but Rosetta?

without Rosetta

**Comment by miyako** [comment]
I mean, does it crash if you switch to rosetta on m2

technically a plugin is 2 different products combined into 1, on mac

**Comment by miyako** [comment]
also is there a different whether you pass the new `FTP_USE_MLSD ` option? because that is the main difference.

**Comment by MatthieuLamp** [comment]
> I mean, does it crash if you switch to rosetta on m2
> 
> technically a plugin is 2 different products combined into 1, on mac

No

**Comment by MatthieuLamp** [comment]
4D crash as soon as the project is opened

**Comment by miyako** [comment]
what about the other question about `FTP_USE_MLSD`?

it would be useful to have a crash report or at least a code snippet that triggers the crash.

I believe your word but "it crashed on Big Sur" is not a useful piece of information.

**Comment by MatthieuLamp** [comment]
I have not tested this command
but the simple fact of having the plugin in the Plugins folder causes 4D to crash on opening.

**Comment by miyako** [comment]
that is new information.

**Comment by miyako** [comment]
I am closing this case as the crash can't be reproduced.

I used Catalina to test..https://github.com/miyako/4d-plugin-curl-v3/releases/tag/4.5.0

**Comment by miyako** [comment]
I think it is a notarisation issue. nothing to do with OS version.

**Comment by miyako** [comment]
try with a new download

**Comment by MatthieuLamp** [comment]
> try with a new download

it's not ok

**Comment by miyako** [comment]
sorry, I can't reproduce the crash.
