### ISSUE TITLE
cURL_FTP_send with large files

### ISSUE THREAD

**Issue by joerg-eyring** [miyako/4d-plugin-curl-v3#2]
Hi Keisuke,
thanks for supplying the new plugin!
We're facing troubles with it, however:
The previous cURL_FTP_Send plugin had a file path as parameter and worked seamlessly even with large files (> 1 GB).
Now we have to supply a blob which is filled with the data to be transmitted.

Here's the issue: Under Windows there's no problem with DOCUMENT TO BLOB when the file is larger than 1 GB, however on macOS 4D refuses to load any file into a blob which is larger than 1 GB.

Maybe it's a problem of 4D, because I tested:

SET BLOB SIZE($blob; 1024*1024*1024-1) -> WORKS
SET BLOB SIZE($blob; 1024*1024*1024) -> DOESN'T WORK

I can't believe that the macOS can't deliver just one more byte of free memory to 4D when the code runs on a machine with 32 GB memory!

Anyway: Since this doesn't seem to work on macOS anymore we need a solution.

Question 1: Is there any option in cURL_FTP_Send so that we can transfer a file in chunks?
Question 2: Is there a setting so we can supply a path name to the plugin instead of a blob (the way the "old" cURL_FTP Plugin worked)?

Thanks and best regards, Jörg

**Comment by miyako** [comment]
* about the BLOB size

plugins work in the stack space of the process, so you might have to allocate enough stack size to the process in order to have a large BLOB.

* about passing a file path

you can use the parameters `READDATA` and `WRITEDATA` instead of in/out BLOBs. see https://github.com/miyako/4d-plugin-curl-v2

**Comment by joerg-eyring** [comment]
Hi Keisuke,

• plugins work in the stack space of the process, so you might have to allocate enough stack size to the process in order to have a large BLOB.

Meanwhile I filed a bug in the forum, since it appears to me as a mystical restriction within 4D under macOS.

• you can use the parameters READDATA and WRITEDATA instead of in/out BLOBs.

Oops, I wasn't aware of this. Thanks for pointing that out. I'll give it a try!

Thanks for your quick response, Jörg
