### ISSUE TITLE
mac/win different libcurl versions 8.4.0/7.74.0-DEV

### ISSUE THREAD

**Issue by ArminDeeg** [miyako/4d-plugin-curl-v3#21]
Hi,

is there a reason, why the windows version uses an nearly three years old libcurl "libcurl-7.74.0-DEV" from Dec 9 2020 and only the mac version uses the latest "libcurl-8.4.0" from Oct 11 2023 ?

taken from the readme, not verified.

Thanks Armin

**Comment by miyako** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/402

just kidding.

**Comment by miyako** [comment]
I updated the library for Mac, to verify whether SFTP was not working because of an issue in the library. indeed, updating solved the issue.

**Comment by miyako** [comment]
it will be updated in 4.6.1
