### ISSUE TITLE
Plugin contains curl 7.74 instead of 8.4

### ISSUE THREAD

**Issue by IngoWolf** [miyako/4d-plugin-curl-v3#22]
Today I downloaded the zip archive from https://github.com/miyako/4d-plugin-curl-v3 and from https://github.com/miyako/4d-plugin-curl-v3/releases/tag/4.6.1. Both plugins are the same (4.6.1). `cURL_VersionInfo` reports `7.74.0-DEV` instead of the expected `8.4.0`:

<img width="2280" alt="Bildschirmfoto 2023-12-19 um 12 55 05 Kopie" src="https://github.com/miyako/4d-plugin-curl-v3/assets/85246043/2f431fd1-b141-4392-8e97-0c806e9a0611">

Test done on Windows with 4D v19R8.

Reason for my need is a problem with NTLM authentication (not working) to an exchange server with extended protection enabled. A test done with curl 8.4 on the command line doesn't show the problem.

THX
Ingo Wolf

**Comment by miyako** [comment]
thank you for the notification. I don't know what happened, but I think it's OK in 4.6.2

**Comment by IngoWolf** [comment]
The download from https://github.com/miyako/4d-plugin-curl-v3 Button `<>Code`->`Download ZIP` is flawed, the file 
`4d-plugin-curl-v3-main`->`curl`->`test`->`Plugins`->`cURL.bundle` can't be used on my Mac (12.7.1 Monterey, M1 Pro), the OS says it's damaged and wants to put it into the trash , 4D (19.2) says (on trying to execute `$vO_VersionInfo:=cURL_VersionInfo()` )

```
The code could not be loaded.
-9949 License or authorization error. (cURL (4.6.2))
-1 The external routine cannot be executed 
```

(in german)

<img width="636" alt="image" src="https://github.com/miyako/4d-plugin-curl-v3/assets/85246043/e93fe36c-b059-476b-841a-2a87bc5baadc">


The plugin from https://github.com/miyako/4d-plugin-curl-v3/releases/download/4.6.2/cURL.zip on the other hand works and shows `8.4.0`. I'll test my NTLM problem asap.

Thank you.

**Comment by miyako** [comment]
> the OS says it's damaged and wants to put it into the trash

that is normal on macOS, by downloading a repository you (or Safari) marks the file as untrustworthy. that is why we have Releases on GitHub.

**Comment by IngoWolf** [comment]
OK.

But on Windows the plugin (https://github.com/miyako/4d-plugin-curl-v3/releases/download/4.6.2/cURL.zip) shows `7.74.0-DEV`:

```
{
	"version": "7.74.0-DEV",
	"version_num": 477696,
	"host": "Windows",
	"features": 23407517,
	"ssl_version": "OpenSSL/1.1.1j (Schannel)",
	"libz_version": "1.2.11",
	"protocols": [
		"dict",
		"file",
		"ftp",
		"ftps",
		"gopher",
		"http",
		"https",
		"imap",
		"imaps",
		"ldap",
		"mqtt",
		"pop3",
		"pop3s",
		"rtsp",
		"scp",
		"sftp",
		"smb",
		"smbs",
		"smtp",
		"smtps",
		"telnet",
		"tftp"
	],
	"libssh_version": "libssh2/1.9.0_DEV",
	"nghttp2_version": "1.42.0"
}
```

**Comment by miyako** [comment]
I see that the file on my PC is good but for some reason Git is not pushing it to origin.

**Comment by miyako** [comment]
let me rebuild (I always have to build on Mac after PC for notarisation)

**Comment by miyako** [comment]
could you please download again?

https://github.com/miyako/4d-plugin-curl-v3/releases/tag/4.6.2

**Comment by IngoWolf** [comment]
Now it's fine:

```
{
	"version": "8.4.0",
	"version_num": 525312,
	"host": "aarch64-apple-darwin21.6.0",
	"features": 1441743773,
	"ssl_version": "(SecureTransport) OpenSSL/3.1.4",
	"libz_version": "1.2.11",
	"protocols": [
		"dict",
		"file",
		"ftp",
		"ftps",
		"gopher",
		"gophers",
		"http",
		"https",
		"imap",
		"imaps",
		"ldap",
		"ldaps",
		"mqtt",
		"pop3",
		"pop3s",
		"rtmp",
		"rtmpe",
		"rtmps",
		"rtmpt",
		"rtmpte",
		"rtmpts",
		"rtsp",
		"scp",
		"sftp",
		"smb",
		"smbs",
		"smtp",
		"smtps",
		"telnet",
		"tftp"
	],
	"libssh_version": "libssh2/1.11.0",
	"brotli_version": "1.0.9",
	"nghttp2_version": "1.58.0",
	"zstd_version": "1.5.1"
}

{
	"version": "8.4.0-DEV",
	"version_num": 525312,
	"host": "Windows",
	"features": 1575833501,
	"ssl_version": "OpenSSL/3.2.0 (Schannel)",
	"libz_version": "1.3",
	"protocols": [
		"dict",
		"file",
		"ftp",
		"ftps",
		"gopher",
		"gophers",
		"http",
		"https",
		"imap",
		"imaps",
		"ldap",
		"ldaps",
		"mqtt",
		"pop3",
		"pop3s",
		"rtsp",
		"scp",
		"sftp",
		"smb",
		"smbs",
		"smtp",
		"smtps",
		"telnet",
		"tftp"
	],
	"libidn": "2.3.4",
	"libssh_version": "libssh2/1.11.0",
	"brotli_version": "1.1.0",
	"nghttp2_version": "1.58.0",
	"zstd_version": "1.5.5"
}
```

Many thanks
