### ISSUE TITLE
OpenSSL/3.1.4 Error

### ISSUE THREAD

**Issue by Angel-Vazquez** [miyako/4d-plugin-curl-v3#27]
When using cURL to download a file from Amazon AWS S3 bucket using cURL command, the following error is given: 
`OpenSSL/3.1.4: error:80000002:system library::No such file or directory`

However when using the native macOS cURL command the file is downloaded without an issue.

```4d
var $curl; $response: Object

$curl:=new object(\
"URL"; "<url_from_s3.amazonaws.com/keys>"; \
"DEBUG": Get 4D Folder (Logs folder); \
"WRITEDATA"; System folder(Desktop)+"sample_001.zip"\
)

$response:=cURL($curl) // $response.status = 35
```

**Comment by miyako** [comment]
for error 60 (not 35)

https://github.com/miyako/4d-plugin-curl-v3/blob/main/curl/test/Project/Sources/Methods/TEST_https.4dm

**Comment by miyako** [comment]
> "DEBUG": Get 4D Folder (Logs folder)

care to share the log files?

**Comment by miyako** [comment]
alway good practice to do a quick search (or use AI, if you like...) the error message before asking for help from a real person

https://github.com/beyondcode/expose/issues/391

**Comment by miyako** [comment]
even though the plugin is using a static library, the paths may be hard coded by default.

**Comment by Angel-Vazquez** [comment]
> > "DEBUG": Get 4D Folder (Logs folder)
> 
> care to share the log files?

If you wish to have the CURLINFO_SSL_DATA_@ files I can send those also, but the CURLINFO_TEXT.log is:
`Host redacted.s3.amazonaws.com:443 was resolved.
IPv6: (none)
IPv4: X.X.X.X, Y.Y.Y.Y, Z.Z.Z.Z
  Trying 3.5.25.88:443...
Connected to redacted.s3.amazonaws.com (X.X.X.X) port 443
ALPN: curl offers h2,http/1.1
TLSv1.3 (OUT), TLS handshake, Client hello (1):
TLSv1.3 (IN), TLS handshake, Server hello (2):
TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
TLSv1.3 (IN), TLS handshake, Certificate (11):
TLSv1.3 (OUT), TLS alert, unknown CA (560):
OpenSSL/3.3.0: error:80000002:system library::No such file or directory
Closing connection`

> do you or don't you have problems with other URLs? is the problem specific to Amazon S3 bucket? (B.T.W, I don't use Amazon (for anything, actually, not even Prime Video) and I can't confirm your report without an actual URL.

I can provide the code snippet via messages if you'd prefer. Considering the data is somewhat sensitive, I'd prefer not to post publicly.

> the latest version uses OpenSSL/3.3.0 so your error suggest you are using an old version.
> 
> keep in mind that OpenSSL requires Monterey minimum. in general, you should always specify your OS version when talking about a potential bug.

Currently running macOS Sonoma 14.4.1, 4D 20R2 (100434), and v4.7.1 of your plugin.

**Comment by miyako** [comment]
I think you should specify CACERT.

**Comment by Angel-Vazquez** [comment]
> I think you should specify [CAINFO](https://curl.se/libcurl/c/CURLOPT_CAINFO.html) or else disable [SSL_VERIFYPEER](https://curl.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html)

You're correct. Setting "SSL_VERIFYPEER" to 0 allows the curl plugin to download the ~550 MB zip file.
