### ISSUE TITLE
How to use curl -d ?

### ISSUE THREAD

**Issue by ArminDeeg** [miyako/4d-plugin-curl-v3#28]
To initiate a sipgate call with curl, there is the following sample

curl -X POST https://api.sipgate.com/v2/sessions/calls \
  -u 'your_sipgate_token:your_sipgate_secret' \
  -H 'Content-Type: application/json' \
  -d '{
        "caller": "+4915799912345",         // Deine Mobiltelefonnummer
        "callee": "+4930123456789",         // Die Ziel-Festnetznummer
        "device": "your_device_id"          // Die ID deines Gerätes bei sipgate
      }'

Inside the documentation I miss the DATA option, asking ChatGPT how to translate the curl -d option to libcurl, I get the answer to use the libcurl option POSTFIELDS which is not supported inside the plugin.

do you have an idea how to transmit the data option with CURL?

**Comment by ArminDeeg** [comment]
I meant, how to transmit the data option with your libcurl plugin

**Comment by miyako** [comment]
according to the docs, the [`POSTFIELDS`](https://curl.se/libcurl/c/CURLOPT_POSTFIELDS.html) option "is a normal application/x-www-form-urlencoded kind".

I don't see how this is different to `READ`.

for instance, you should see the desired effect with:

```4d
$options:={}
$options.URL:="http://localhost/test"
$options.SSL_VERIFYPEER:=0
$options.SSL_VERIFYHOST:=0
$options.POST:=1
$options.USERNAME:="your_sipgate_token"
$options.PASSWORD:="your_sipgate_secret"

$d:={\
caller: "+4915799912345"; \
callee: "+4930123456789"; \
device: "your_device_id"\
}

$options.HTTPHEADER:=["Content-Type: application/json"]

var $request; $response : Blob

CONVERT FROM TEXT(JSON Stringify($d); "utf-8"; $request)

$status:=cURL($options; $request; $response)
```
