### ISSUE TITLE
4D quit when using curl

### ISSUE THREAD

**Issue by BARBERIN** [miyako/4d-plugin-curl-v3#29]
Since my  windows 11 as been updated to the version 2024-08 Mise à jour cumulative pour Windows 11 Version 23H2 pour les systèmes x64 (KB5041585), 4D quit after fews seconds when using curl. 
Very rarely it s working but most of time 4D quit for example using cURL_FTP_GetDirList.
Thanks for your help

**Comment by miyako** [comment]
what if you disable Hardware-enforced Stack Protection ?

**Comment by miyako** [comment]
with no detail information about the Windows Defender log there is nothing I can do on my side.

**Comment by miyako** [comment]
https://www.windowslatest.com/2024/08/16/windows-11-kb5041585-ipv6-patch-slows-down-pcs-breaks-vanguard-fails-to-install/

because curl is not a device driver, maybe IPv6 related ?

**Comment by miyako** [comment]
from the article above

> we observed that removing the patch and then turning off IPv6 manually is the best way to handle the problem

**Comment by BARBERIN** [comment]
Thanks for yours informations.
On my PC I don't have Hardware-enforced Stack Protection.
Unfortunatly I desabled IPV6 and  unistalled the windows update. It seems a bit better but  most of time it s not working.
I have to investigate more.
