### ISSUE TITLE
cURL_FTP_Rename - which property has to be set for the new name?

### ISSUE THREAD

**Issue by joerg-eyring** [miyako/4d-plugin-curl-v3#3]
Hi Keisuke,

sorry, but I can't figure out which property in the options-object has to be set for the new name on the ftp-Server.
Maybe you want to give me hint?

Thanks a lot, Jörg

**Comment by miyako** [comment]
you can do a command+F on the [source](https://raw.githubusercontent.com/miyako/4d-plugin-curl-v3/main/curl/4DPlugin-cURL.cpp)

it's `RENAME_TO`
