### ISSUE TITLE
cURL_FTP_PrintDir crashes on Windows with plugin v4.8.2

### ISSUE THREAD

**Issue by blegay** [miyako/4d-plugin-curl-v3#31]
Hi,

Noticed a crashing bug with latest version of 4d-plugin-curl-v3 (v4.8.2)
On Windows only it seems...

It is not systematic, about 50% of calls to this code...

`
var $options : Object
$options:=New object
$options.USE_SSL:="USESSL_ALL"
$options.SSL_VERIFYPEER:=2
$options.SSL_VERIFYHOST:=1
$options.CAINFO:="C:\\Users\\bruno\\4D\\com.ac-consulting\\curllib-component\\cacert.pem"
$options.URL:="ftp://ftp.example.com/backup/"
$options.USERNAME:="***user***"
$options.PASSWORD:="***password***"
$options.FTP_CREATE_MISSING_DIRS:=0

var $error : Object
$error:=cURL_FTP_PrintDir($options)
`

@miyako : contact me privately if you want some credentials for a test server (ftp + ftps)

**Comment by miyako** [comment]
see https://github.com/miyako/4d-plugin-curl-v3/issues/32

**Comment by miyako** [comment]
there is also a report about 

> Windows 11 Version 23H2 pour les systèmes x64 (KB5041585)

https://github.com/miyako/4d-plugin-curl-v3/issues/29

**Comment by blegay** [comment]
Seems solved with v4.8.4

**Comment by blegay** [comment]
Thanks !
