### ISSUE TITLE
cURL_FTP_Send send crashes on Window since 4.8.0

### ISSUE THREAD

**Issue by blegay** [miyako/4d-plugin-curl-v3#32]
Hi,

The following code crashed on Windows with 4D v20.4 LTS

4.7.3 => ok
4.8.0 => crash
4.8.3 => crash

The test was done with a small file... 

+ needs testing large files (> 2Gb)

`
ARRAY TEXT($tt_filePathList; 0)

var $docName : Text
$docName:=Select document(""; "*"; "Select file to send"; 0; $tt_filePathList)

If (ok=1) & (Size of array($tt_filePathList)=1)
	
	var $file : 4D.File
	$file:=File($tt_filePathList{1}; fk platform path)
	
	var $url : Text
	//$url:="ftp://ftp.example.com/backup/"+Generate UUID+$file.extension
	$url:="ftp://ftp.example.com/backup/"+cURL_Escape($file.fullName)
	
	var $options : Object
	$options:=New object
	
	$options.URL:=$url
	
	$options.SSL_VERIFYPEER:=0
	$options.SSL_VERIFYHOST:=0
	$options.USE_SSL:="USESSL_NONE"
	
	$options.USERNAME:="***login***"
	$options.PASSWORD:="***password***"
	
	$options.READDATA:=$file.platformPath
	
	var $data : Blob
	SET BLOB SIZE($data; 0)
	
	var $result : Object
	$result:=cURL_FTP_Send($options; $data)
	
End if 
`

**Comment by miyako** [comment]
I can build a version with older libcurl and openssl from 4.7.3. it there is no crash, the fault is external to the plugin.

**Comment by miyako** [comment]
the release shall be named 4.7.4

**Comment by blegay** [comment]
Hi, 
it works with plugin version 4.7.4 on Windows 10.
I did test with sending a small file and a large file (3 Gb).

Just after that I used version 4.8.3 and it crashed. So version 4.7.4 seems more stable to me.

**Comment by blegay** [comment]
Also the crash could not be reproduced with v4.8.4 :-)

So v4.8.4 seems ok as well (small file, large file) ! :-)
