### ISSUE TITLE
cURL_FTP_Delete doesn't work reliably

### ISSUE THREAD

**Issue by joerg-eyring** [miyako/4d-plugin-curl-v3#4]
Hi Keisuke,

I made extensive tests with your new cURL plugin. Here are my experiences with "cURL_FTP_Delete":

macOS:

SFTP:
$options:=New object
$options.URL:="sftp://ftp.server.de/file.zip"
$options.USERNAME:=$user
$options.PASSWORD:=$pw
$status:=cURL_FTP_Delete($options; "")

$status.status yields 78 -> ?
File is deleted anyway!

Windows:
FTP:
$options:=New object
$options.URL:="ftp://ftp.server.de/file.zip"
$options.USERNAME:=$user
$options.PASSWORD:=$pw
$status:=cURL_FTP_Delete($options; "")

-> Crash of 4D

FTPS:
$options:=New object
$options.URL:="ftp://ftp.server.de/file.zip"
$options.USE_SSL:="USESSL_TRY"  //Implicit FTPS
$options.USERNAME:=$user
$options.PASSWORD:=$pw
$status:=cURL_FTP_Delete($options; "")

-> Crash of 4D

SFTP:
$options:=New object
$options.URL:="sftp://ftp.server.de/file.zip"
$options.USERNAME:=$user
$options.PASSWORD:=$pw
$status:=cURL_FTP_Delete($options; "")

-> Crash of 4D

Regards, Jörg

All tests were performed with v18R6 build 264867 on either macOS 10.14.6 or Windows 10 10.0.19043 (21H1).

**Comment by joerg-eyring** [comment]
Hi Keisuke,
when can we expect a new version of the plugin where at least the crashes on Windows are fixed?
Thanks and best regards, Jörg

**Comment by miyako** [comment]
I confirm that ftp protocol+`USE_SSL` consumes lots of CPU and ultimately ends in error 35. but no crash.

ftps+`SSL_VERIFYPEER:=0` is the workaround.

**Comment by miyako** [comment]
please test 4.1.0

**Comment by joerg-eyring** [comment]
> please test 4.1.0

Hi Keisuke,

I tested 4.1.0 (specifically with FTPS) on macOS and Windows -> no success (at least the crashes on Windows are gone)

> ftps protocol+SSL_VERIFYPEER:=0 is the workaround.

This doesn't seem to work:

On **macOS**:
A)
$options:=New object
$options.URL:="ftps://ftp.server.de/file.zip"
$options.USERNAME:=$user
$options.PASSWORD:=$pw
$options.SSL_VERIFYPEER:=0
$status:=cURL_FTP_Delete($options; "")

-> $status.status yields 7 -> CURLE_COULDNT_CONNECT (7)

B)
$options:=New object
$options.URL:="ftp://ftp.server.de/file.zip"
$options.USERNAME:=$user
$options.PASSWORD:=$pw
$options.SSL_VERIFYPEER:=0
$status:=cURL_FTP_Delete($options; "")

-> $status.status yields 67 -> CURLE_LOGIN_DENIED (67)

C)
$options:=New object
$options.URL:="ftp://ftp.server.de/file.zip"
$options.USE_SSL:="USESSL_TRY" //Implicit FTPS
$options.USERNAME:=$user
$options.PASSWORD:=$pw
$options.SSL_VERIFYPEER:=0
$status:=cURL_FTP_Delete($options; "")

$status.status yields 0 -> OK
File is deleted.

My conclusion: $options.USE_SSL:="USESSL_TRY" is NECESSARY at least for macOS to work. Protocol "ftps://" doesn't seem to work on macOS

On **Windows**:
All suggested scenarios (A, B) have been tested on Windows.
In addition scenario C ("USE_SSL" - which works properly on macOS) was tested.
All options resulted in: $status.status yields 28 -> CURLE_OPERATION_TIMEDOUT (28)

Please have a look at this issue, since we rely on the proper functionality of your cURL-Plugin for a big customer project!

Many thanks and best regards, Jörg

**Comment by joerg-eyring** [comment]
One more thing (version 4.1.0):

How comes that on **macOS**

SFTP:
$options:=New object
$options.URL:="sftp://ftp.server.de/file.zip"
$options.USERNAME:=$user
$options.PASSWORD:=$pw
$status:=cURL_FTP_Delete($options; "")

still yields $status.status 78 (CURLE_REMOTE_FILE_NOT_FOUND (78)) but the file is deleted anyway??

Regards, Jörg

**Comment by miyako** [comment]
the crash for SFTP when `SSH_AUTH_TYPES` seems to be caused by the library defaulting to AUTH_KEYBOARD. I have disabled this mode in 4.1.2.

**Comment by miyako** [comment]
I did not reproduce a crash with ftp:+`USESSL_TRY` but I did get an error 35. the scheme is FTP is status. no problems with ftps: URL.

**Comment by miyako** [comment]
> still yields $status.status 78 (CURLE_REMOTE_FILE_NOT_FOUND (78)) but the file is deleted anyway??

the plugins is using 

`CURLOPT_POSTQUOTE` for 

* Rename (SFTP, FTPS, FTP)
* Delete, RemoveDir (FTPS, FTP)

`CURLOPT_QUOTE` for

* Delete, RemoveDir (SFTP)
* MakeDir (SFTP, FTPS, FTP)

I could change Delete to `CURLOPT_POSTQUOTE`, to see what happens.
