### ISSUE TITLE
cURL_FTP_MakeDir doesn't work reliably

### ISSUE THREAD

**Issue by joerg-eyring** [miyako/4d-plugin-curl-v3#5]
Hi Keisuke,

I made extensive tests with your new cURL plugin. Here are my experiences with "cURL_FTP_MakeDir":

macOS:
FTP:
$options:=New object
$options.URL:="ftp://ftp.server.de/subDir/"
$options.USERNAME:=$user
$options.PASSWORD:=$pw
$status:=cURL_FTP_MakeDir($options; "")

$status.status yields 0 -> OK
Directory is created.

FTPS:
$options:=New object
$options.URL:="ftp://ftp.server.de/subDir/"
$options.USE_SSL:="USESSL_TRY" //Implicit FTPS
$options.USERNAME:=$user
$options.PASSWORD:=$pw
$status:=cURL_FTP_MakeDir($options; "")

$status.status yields 21 (for the FIRST try)
$status.status yields 0 (for the SECOND try)
Directory is created at the SECOND try.

SFTP:
$options:=New object
$options.URL:="sftp://ftp.server.de/subDir/"
$options.USERNAME:=$user
$options.PASSWORD:=$pw
$status:=cURL_FTP_MakeDir($options; "")

$status.status yields 0 -> OK
Directory is created.

Windows:
FTP:
$options:=New object
$options.URL:="ftp://ftp.server.de/subDir/"
$options.USERNAME:=$user
$options.PASSWORD:=$pw
$status:=cURL_FTP_MakeDir($options; "")

$status.status yields 0 -> OK
Directory is created.

FTPS:
$options:=New object
$options.URL:="ftp://ftp.server.de/subDir/"
$options.USE_SSL:="USESSL_TRY" //Implicit FTPS
$options.USERNAME:=$user
$options.PASSWORD:=$pw
$status:=cURL_FTP_MakeDir($options; "")

$status.status yields 21 (for the FIRST try)
$status.status yields 60 (for the SECOND and subsequent tries)
Directory is NOT created.

SFTP:
$options:=New object
$options.URL:="sftp://ftp.server.de/subDir/"
$options.USERNAME:=$user
$options.PASSWORD:=$pw
$status:=cURL_FTP_MakeDir($options; "")

$status.status yields 0 -> OK
Directory is created.

Regards, Jörg

All tests were performed with v18R6 build 264867 on either macOS 10.14.6 or Windows 10 10.0.19043 (21H1).

**Comment by miyako** [comment]
in general, don't use `USE_SSL` specify the protocol as "ftps".

status is `78` (file not found) when the given URL does not end with a / (but it is created).

**Comment by miyako** [comment]
crash when the URL is omitted.

**Comment by miyako** [comment]
the plugin looks at the protocol to decide whether to use TLS or not. not sure if `USE_SSL` is relevant.

**Comment by joerg-eyring** [comment]
`"USE_SSL"` seems to be relevant - at least on macOS and for cURL_FTP_Delete - leaving it out doesn't work at all. "ftps://" doesn't seem to be the solution :-(

Please see the my remarks for the issue "cURL_FTP_Delete doesn't work reliably".

BTW: As you see in my examples, the URL ends with a trailing slash ("/") to specify the dir to be created.

**Comment by miyako** [comment]
the plugins is using 

`CURLOPT_POSTQUOTE` for 

* Rename (SFTP, FTPS, FTP)
* Delete, RemoveDir (FTPS, FTP)

`CURLOPT_QUOTE` for

* MakeDir (SFTP, FTPS, FTP)

**Comment by miyako** [comment]
I am sorry I do not reproduce the issue.

on both platforms, `cURL_FTP_MakeDir` creates folder on first attempt and ``USE_SSL` can be omitted (in status, effetiveMethod is HEAD, scheme is FTPS)
