### ISSUE TITLE
Crashes calling cURL on macOS

### ISSUE THREAD

**Issue by joerg-eyring** [miyako/4d-plugin-curl-v3#6]
Hi Keisuke,
with this new plugin we're observing crashes on macOS (10.14.6) and 4D v19 when the plugin method "cURL" is called. Please see attached crash log.
With the predecessor plugin and v18 there weren't any crashes.
Maybe you have an idea what's the reason.
Regards, Jörg
[TOPIX Client_2021-07-05-094911_sfrs-MBP-15.crash.zip](https://github.com/miyako/4d-plugin-curl-v3/files/6815713/TOPIX.Client_2021-07-05-094911_sfrs-MBP-15.crash.zip)

**Comment by miyako** [comment]
did you use v.4.0.2?

**Comment by miyako** [comment]
please test 4.1.0
