### ISSUE TITLE
Bug in 4d-plugin-curl-v3 4.1.0 with HTTPHEADER

### ISSUE THREAD

**Issue by IngoWolf** [miyako/4d-plugin-curl-v3#8]
I upgraded the curl plugin to 4.1.0, and now i can’t set custom http headers anymore. Following request

    $options:=New object
    $options.URL:="https://api-zoug.moments.dad-group.com/api/v5/area"
    $options.HTTPHEADER:=New collection("accept: application/json";"pageLimit: 10";"pageCurrent: 1";"Authorization: Basic YXBpLmRvc2dyb3VwQGRvcy1nc206UGhhbGNvbjE1")

    C_BLOB($request;$reponse)
    $status:=cURL ($options;$request;$reponse)

sends this headers:

    GET /api/v5/area HTTP/2
    Host: api-zoug.moments.dad-group.com
    accept: */*

Tested in v18R5 and v19.0 on MacOS 10.14.6 and in v18R5 on Windows 10 Pro.

Thanks for looking after
Ingo Wolf

**Comment by miyako** [comment]
could you please try 4.1.1.

**Comment by IngoWolf** [comment]
Hello,

setting custom headers works in 4.1.1.

Thanks
Ingo Wolf
