### ISSUE TITLE
cURL_FTP_Send: SFTP with public key authentication doesn't work

### ISSUE THREAD

**Issue by joerg-eyring** [miyako/4d-plugin-curl-v3#9]
Hi Keisuke,

for another customer project we need SFTP transfer with public key authentication.
Whatever I try, I can't get it working.
On macOS the result is always (status=67), while on Windows the operation times out (status=28).

**Environment:**
MacOS 10.15 resp. Windows 10
4D v19 269306
cURL Plugin 4.1.0

**Here's the simple code:**
C_OBJECT($options; $status)
C_BLOB($data)

SET BLOB SIZE($data; 0)
$options:=New object

$options.USERNAME:="username"

$options.READDATA:=System folder(Desktop)+"upload.zip"
$options.UPLOAD:=1
$options.FTP_CREATE_MISSING_DIRS:=1

$options.SSH_AUTH_TYPES:=1  //CURLSSH_AUTH_PUBLICKEY
$path:=System folder(Desktop)+"private.pem"
If (Is macOS)
     $path:=Convert path system to POSIX($path)
End if 
$options.SSH_PRIVATE_KEYFILE:=$path
$path:=System folder(Desktop)+"public.pem"
If (Is macOS)
     $path:=Convert path system to POSIX($path)
End if 
$options.SSH_PUBLIC_KEYFILE:=$path

$options.SSL_VERIFYPEER:=0 
$options.SSL_VERIFYHOST:=0 

$options.URL:="sftp://"+"ftp.company.com"+"/test/"+"upload.zip"

$status:=cURL_FTP_Send($options; $data; "")

I've been playing with different syntaxes for the path names (System or POSIX - couldn't find any exact information for how to specify them) to no avail. Maybe you can clarify what syntax for path names should be used (macOS and/or Windows).

What option did I forget to set?
BTW: Trying the same with a call of "cURL" of the Plugin yields the same results.

Many thanks and regards,
Jörg

NB: The keys are valid since native ftp apps like FileZilla or Forklift work flawlessly.

**Comment by miyako** [comment]
you do not have to convert path to POSIX on Mac. just pass the HFS platform path.

I finally found the time to setup SFTP using 2 Macs. the code that works look like this:

```4d
C_OBJECT($options;$status)
C_BLOB($data)

SET BLOB SIZE($data;0)
$options:=New object

$options.USERNAME:="miyako"
$options.READDATA:=Folder(fk resources folder).file("upload.zip").platformPath
$options.FTP_CREATE_MISSING_DIRS:=1
  //crash when this is omitted; TODO: CURLSSH_AUTH_KEYBOARD should be disabled
$options.SSH_AUTH_TYPES:=1  //CURLSSH_AUTH_PUBLICKEY
$options.SSH_PUBLIC_KEYFILE:=Folder(fk desktop folder).file("id_rsa.pub").platformPath

$options.SSL_VERIFYPEER:=0
$options.SSL_VERIFYHOST:=0

$options.URL:="sftp://100.64.1.57/Users/miyako/Desktop/test-1.zip"

$status:=cURL_FTP_Send ($options;$data;"")
```

**Comment by miyako** [comment]
you should not need to specify  `SSH_PRIVATE_KEYFILE`. there is a libcurl [trick](https://curl.se/libcurl/c/CURLOPT_SSH_PUBLIC_KEYFILE.html) to get the public key from the private key and password, but in general you just specify the public key.

SSH2 may refuse the public key with the error 

```
 "Permissions 0644 for 'id_rsa.pub' are too open"
```

in which case you need to `chmod`.

**Comment by miyako** [comment]
I think I reproduce the issue, SSH2 caches connection credentials so the success was from a previous user:pass session. need to investigate more.

**Comment by miyako** [comment]
I've installed `brew curl` (SFTP is disabled in preinstalled curl) I get the same result as the plugin

```
curl -u miyako: --pubkey ~/.ssh/id_rsa.pub sftp://100.64.1.57/Users/miyako/Desktop/TableForms.zip
curl: (67) Authentication failure
```

**Comment by miyako** [comment]
meanwhile, this sees to work

```4d
If (True)
	$options.KEYPASSWD:="pass"
	$options.SSH_PRIVATE_KEYFILE:=Folder(fk desktop folder).file("id_rsa").platformPath
Else 
	$options.SSH_PUBLIC_KEYFILE:=Folder(fk desktop folder).file("id_rsa.pub").platformPath
End if 
```
